added timeout for load captcha
aemsites/mmsg-oly pull request #191
Opened 2024-08-08 11:19 UTC by mojojain

- Before: https://main--mmsg-oly--aemsites.hlx.live/
- After: https://google-recaptcha--mmsg-oly--aemsites.hlx.live/

2024-08-08 15:33 UTC, mrugesh-adobe requested changes

2024-08-08 15:33 UTC, mrugesh-adobe commented on blocks/form/form.js
>  const googleRecaptchaKey = '6LcKcVQpAAAAAKJxn3Mg1o1ca9jjrEJFDigV4zwa';
<img width="556" alt="image" src="https://github.com/user-attachments/assets/bb309ead-62ea-433a-87ba-0d4234ecc753">
add all keys and API url data into config.js. Will explain you how to get them.

2024-08-09 09:51 UTC, roohibengani approved these changes

2024-08-09 11:02 UTC, mrugesh-adobe approved these changes

2024-08-09 11:02 UTC, merged