column block video variation - excluding video cta action
aemsites/mmsg-oly pull request #47
Opened 2024-07-16 12:06 UTC by VarsTheMars

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:

- Before: https://main--mmsg-oly--aemsites.hlx.live/
- After: https://<branch>--mmsg-oly--aemsites.hlx.live/

2024-07-16 12:33 UTC, roohibengani approved these changes

2024-07-16 12:34 UTC, mrugesh-adobe requested changes

2024-07-16 12:34 UTC, mrugesh-adobe commented on blocks/columns/columns.css
> +        height: 280px;
this CSS will be affected to other variation of column block. @VarsTheMars

2024-07-16 12:34 UTC, mrugesh-adobe commented on blocks/columns/columns.css
> +    color: white; /* change to desired color */
use variable here

2024-07-17 10:27 UTC, VarsTheMars commented on blocks/columns/columns.css
> +        height: 280px;
the CSS changes has been reverted and updated @mrugesh-adobe

2024-07-17 10:28 UTC, VarsTheMars commented on blocks/columns/columns.css
> +    color: white; /* change to desired color */
added the global variable here

2024-07-17 12:45 UTC, roohibengani approved these changes

2024-07-18 08:15 UTC, mrugesh-adobe approved these changes

2024-07-18 08:15 UTC, merged